
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSUREASIGN ID N RE SUresultado : sresultado : ID ASIGN ss : Ns : IDs : s SU s\n        | s RE s'
    
_lr_action_items = {'ID':([0,5,6,7,],[3,9,9,9,]),'N':([0,5,6,7,],[4,4,4,4,]),'$end':([1,2,3,4,8,9,10,11,],[0,-1,-4,-3,-5,-4,-6,-2,]),'SU':([2,3,4,8,9,10,11,],[5,-4,-3,-5,-4,-6,5,]),'RE':([2,3,4,8,9,10,11,],[6,-4,-3,-5,-4,-6,6,]),'ASIGN':([3,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'resultado':([0,],[1,]),'s':([0,5,6,7,],[2,8,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> resultado","S'",1,None,None,None),
  ('resultado -> s','resultado',1,'p_resultado','main.py',40),
  ('resultado -> ID ASIGN s','resultado',3,'p_asignacion','main.py',44),
  ('s -> N','s',1,'p_expr_num','main.py',48),
  ('s -> ID','s',1,'p_expr_id','main.py',52),
  ('s -> s SU s','s',3,'p_expr_op','main.py',60),
  ('s -> s RE s','s',3,'p_expr_op','main.py',61),
]
